name: mern-app

services:
  api: 
    build:
      context: ./app/backend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: 
      - path: ./app/backend/backend.env
    ports:
      - 3000:3000


    
