### CREATE GRANT
POST http://localhost:3000/grants/create HTTP/1.1
content-type: application/json

{
    "foundation": "Juan Young Trust",
    "notes": "focuses on youth development and education",
    "date": "09-03-24",
    "ask": "$3,000",
    "award": "$0",
    "currStatus": "pending"
}

### RETRIEVE ALL GRANTS 
GET http://localhost:3000/grants/all HTTP/1.1

### RETRIEVE GRANT BY ID
GET http://localhost:3000/grants/get/66b0048704cd2e9e7c719e8c HTTP/1.1


### UPDATE GRANT
PUT http://localhost:3000/grants/66b8094dccab0e560470bc74 HTTP/1.1
content-type: application/json

{
    "foundation": "Autzen Foundation",
    "notes": "focuses on youth development and education",
    "date": "09-03-24",
    "ask": "$3,000",
    "award": "$2,500",
    "currStatus": "awarded"
}

### DELETE GRANT
DELETE http://localhost:3000/grants/66b0048704cd2e9e7c719e8c

### LOGIN USER
POST http://localhost:3000/user/login HTTP/1.1
content-type: application/json

{
    "email": "test@gmail.com",
    "password": "mypass12345"
}

### LOGIN USER
POST http://localhost:3000/user/login HTTP/1.1
content-type: application/json

{
    "email": "lalala@msn.com",
    "password": "alkfhkfJ789!"
}

### LOGIN USER 2
POST http://localhost:3000/user/login HTTP/1.1
content-type: application/json

{
    "email": "oh_hello@msn.com",
    "password": "alkfhkfJ789!"
}

### SIGN UP USER
POST http://localhost:3000/user/signup HTTP/1.1
content-type: application/json

{
    "email": "test@gmail.com",
    "password": "mypass12345"
}

### SIGN UP USER 2
POST http://localhost:3000/user/signup HTTP/1.1
content-type: application/json

{
    "email": "dummy@gmail.com",
    "password": "hi"
}

### SIGN UP USER 3
POST http://localhost:3000/user/signup HTTP/1.1
content-type: application/json

{
    "email": "oh_hello_baby@msn.com",
    "password": "alkfhkfJ789!"
}